# Generated by Django 2.2.7 on 2019-11-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='time',
            field=models.IntegerField(default=1800),
            preserve_default=False,
        ),
    ]
