# Generated by Django 2.2.7 on 2019-11-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_answer_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='category',
            field=models.CharField(choices=[('General Knowledge', 'General Knowledge'), ('Entertainment: Books', 'Entertainment: Books'), ('Entertainment: Film', 'Entertainment: Film'), ('Entertainment: Music', 'Entertainment: Music'), ('Entertainment: Musicals & Theatres', 'Entertainment: Musicals & Theatres'), ('Entertainment: Television', 'Entertainment: Television'), ('Entertainment: Video Games', 'Entertainment: Video Games'), ('Entertainment: Board Games', 'Entertainment: Board Games'), ('Science & Nature', 'Science & Nature'), ('Science: Computers', 'Science: Computers'), ('Science: Mathematics', 'Science: Mathematics'), ('Mythology', 'Mythology'), ('Sports', 'Sports'), ('Geography', 'Geography'), ('History', 'History'), ('Politics', 'Politics'), ('Art', 'Art'), ('Celebrities', 'Celebrities'), ('Animals', 'Animals'), ('Vehicles', 'Vehicles'), ('Entertainment: Comics', 'Entertainment: Comics'), ('Science: Gadgets', 'Science: Gadgets'), ('Entertainment: Japanese Anime & Manga', 'Entertainment: Japanese Anime & Manga'), ('Entertainment: Cartoon & Animations', 'Entertainment: Cartoon & Animations')], max_length=255),
        ),
    ]
